### ISSUE TITLE
Write a tutorial for using `yalc` in the handbook

### ISSUE THREAD

**Issue by seveibar** [tscircuit/handbook#2]
To do this, you MUST be someone who uses yalc all the time- don't try this if you're not a frequent user! (maybe @Abse2001 @ShiboSoftwareDev or @AnasSarkiz )

/bounty $15

**Comment by Abse2001** [comment]
/attempt #2

<div id="algora-attempt" />

| [Algora profile](https://console.algora.io/@/Abse2001) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @Abse2001 | 20 tscircuit bounties | <div align="center">TypeScript</div> | <div align="center">﹟476</div> | [Cancel attempt](https://console.algora.io/api/bounties/cm55qcc5s000cif03wkuw00gs/cancel-attempt) |

**Comment by Anshgrover23** [comment]
/attempt #2

<div id="algora-attempt" />

| [Algora profile](https://console.algora.io/@/Anshgrover23) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @Anshgrover23 | &nbsp;&nbsp;&nbsp;19 tscircuit bounties <br/> + 3 bounties from 3 projects | <div align="center">TypeScript, JavaScript, <br />Go & more</div> | <div align="center">﹟427</div> | [Cancel attempt](https://console.algora.io/api/bounties/cm55qcc5s000cif03wkuw00gs/cancel-attempt) |
